spring.application.name=financeiro-simples

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/financeirodb}
spring.datasource.username=${DB_USERNAME:teste}
spring.datasource.password=${DB_PASSWORD:teste}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

security.jwt.secret=${JWT_SECRET}
security.expiration-seconds=${EXPIRATION_TIME}

security.cookie.secure=${JWT_COOKIE_SECURE:false}

currency.url=https://api.currencyfreaks.com/v2.0
currency.api-key=${CURRENCY_FREAKY_API_KEY}

springdoc.swagger-ui.with-credentials=true

app.cors.allowed-origins="http://localhost:8080,http://localhost:4200"